### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bbigras** [nivrrex/excel#1]
I have this error while trying to open a xlsm file.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x423113]

goroutine 1 [running]:
github.com/mattn/go-ole.getIDsOfName(0x0, 0x3a1b90, 0x1, 0x1, 0xc0800000a8, ...)
    d:/dev/go/gopath/src/github.com/mattn/go-ole/idispatch.go:74 +0x163
github.com/mattn/go-ole.(*IDispatch).GetIDsOfName(0x0, 0x3a1b90, 0x1, 0x1, 0x0, ...)
    d:/dev/go/gopath/src/github.com/mattn/go-ole/idispatch.go:41 +0x81
github.com/mattn/go-ole/oleutil.GetProperty(0x0, 0x4cc840, 0x6, 0x3a1d88, 0x1, ...)
    d:/dev/go/gopath/src/github.com/mattn/go-ole/oleutil/oleutil.go:61 +0xb2
github.com/mattn/go-ole/oleutil.MustGetProperty(0x0, 0x4cc840, 0x6, 0x3a1d88, 0x1, ...)
    d:/dev/go/gopath/src/github.com/mattn/go-ole/oleutil/oleutil.go:70 +0x5f
github.com/nivrrex/excel.ExcelBookOpen(0x4ed710, 0x56, 0x0, 0x0, 0x4c9f00, ...)
    d:/dev/go/gopath/src/github.com/nivrrex/excel/excel.go:80 +0x4f6
main.main()
    D:/Dev/go/go-test-excel/gotestexcel.go:11 +0x70

exit status 2
```

code

```
fExcel, errOpen := excel.ExcelBookOpen(filePath, false, 0, "", "")
if errOpen != nil {
    log.Panic(errOpen)
}
```

go version go1.1.2 windows/amd64

**Comment by nivrrex** [comment]
maybe you use "file.xls", please use the absolute path.
you can use "T:\file.xls".

**Comment by bbigras** [comment]
OK I tried again. It seems the API changed and I'm not sure if I'm using it the right way.

I don't have the same error as before. Should I open a new issue or try to rename this one?

``` go
package main

import "github.com/nivrrex/excel"

func main() {
    var excelFile excel.Excel

    _, err := excelFile.Open("d:\\test.xlsm")
    if err != nil {
        panic(err)
    }
    excelFile.Close()
}
```

```
D:\Dev\go\Tests\go-excel> go run .\texc.go
fatal error: freelist empty

goroutine 16 [running]:
runtime.throw(0x570fcb)
        c:/go/src/pkg/runtime/panic.c:520 +0x7e fp=0x273908 sp=0x2738f0
runtime.MCentral_CacheSpan(0x58de38)
        c:/go/src/pkg/runtime/mcentral.c:96 +0x23f fp=0x273938 sp=0x273908
runtime.MCache_Refill(0x230000, 0xc000000002)
        c:/go/src/pkg/runtime/mcache.c:78 +0x127 fp=0x273968 sp=0x273938
runtime.mallocgc(0xa, 0x4af3c1, 0x1)
        c:/go/src/pkg/runtime/malloc.goc:125 +0x4fa fp=0x2739d0 sp=0x273968
cnew(0x4af3c0, 0x5, 0xc000000001)
        c:/go/src/pkg/runtime/malloc.goc:836 +0xc8 fp=0x2739f0 sp=0x2739d0
runtime.cnewarray(0x4af3c0, 0x5)
        c:/go/src/pkg/runtime/malloc.goc:849 +0x41 fp=0x273a10 sp=0x2739f0
makeslice1(0x4ab860, 0x5, 0x5, 0x273a70)
        c:/go/src/pkg/runtime/slice.goc:55 +0x54 fp=0x273a28 sp=0x273a10
runtime.makeslice(0x4ab860, 0x5, 0x5, 0x0, 0x5, 0x5)
        c:/go/src/pkg/runtime/slice.goc:36 +0xba fp=0x273a58 sp=0x273a28
unicode/utf16.Encode(0xc082005120, 0x5, 0x8, 0x0, 0x0, 0x0)
        c:/go/src/pkg/unicode/utf16/utf16.go:64 +0x9f fp=0x273af0 sp=0x273a58
syscall.UTF16FromString(0x4ead50, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/syscall/syscall_windows.go:40 +0x14f fp=0x273b38 sp=0x273af0
syscall.StringToUTF16(0x4ead50, 0x4, 0x0, 0x0, 0x0)
        c:/go/src/pkg/syscall/syscall_windows.go:24 +0x5f fp=0x273bb0 sp=0x273b38
syscall.StringToUTF16Ptr(0x4ead50, 0x4, 0x1)
        c:/go/src/pkg/syscall/syscall_windows.go:58 +0x38 fp=0x273bf8 sp=0x273bb0
github.com/mattn/go-ole.getIDsOfName(0x18e5f8, 0x273d38, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        d:/dev/go/gopath/src/github.com/mattn/go-ole/idispatch.go:63 +0xf2 fp=0x273c98 sp=0x273bf8
github.com/mattn/go-ole.(*IDispatch).GetIDsOfName(0x18e5f8, 0x273d38, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        d:/dev/go/gopath/src/github.com/mattn/go-ole/idispatch.go:41 +0x87 fp=0x273ce8 sp=0x273c98
github.com/mattn/go-ole/oleutil.CallMethod(0x18e5f8, 0x4ead50, 0x4, 0x273ea0, 0x3, 0x3, 0x0, 0x0, 0x0)
        d:/dev/go/gopath/src/github.com/mattn/go-ole/oleutil/oleutil.go:47 +0xe3 fp=0x273d80 sp=0x273ce8
github.com/mattn/go-ole/oleutil.MustCallMethod(0x18e5f8, 0x4ead50, 0x4, 0x273ea0, 0x3, 0x3, 0xc0820004b0)
        d:/dev/go/gopath/src/github.com/mattn/go-ole/oleutil/oleutil.go:56 +0x65 fp=0x273dd0 sp=0x273d80
github.com/nivrrex/excel.(*Excel).Open(0x273f18, 0x4f0530, 0xc, 0x4af5c0, 0x0, 0x0)
        d:/dev/go/gopath/src/github.com/nivrrex/excel/excel.go:58 +0x50f fp=0x273ed8 sp=0x273dd0
main.main()
        D:/Dev/go/Tests/go-excel/texc.go:8 +0x51 fp=0x273f50 sp=0x273ed8
runtime.main()
        c:/go/src/pkg/runtime/proc.c:247 +0x144 fp=0x273fa8 sp=0x273f50
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445 fp=0x273fb0 sp=0x273fa8
created by _rt0_go
        c:/go/src/pkg/runtime/asm_amd64.s:97 +0x12c

goroutine 19 [finalizer wait]:
runtime.park(0x414a90, 0x575c00, 0x574649)
        c:/go/src/pkg/runtime/proc.c:1369 +0xac
runtime.parkunlock(0x575c00, 0x574649)
        c:/go/src/pkg/runtime/proc.c:1385 +0x42
runfinq()
        c:/go/src/pkg/runtime/mgc0.c:2644 +0xdd
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445
exit status 2
```

**Comment by nivrrex** [comment]
can you leave your system\excel\golang version?
I only tested in 32-bit windows7, excel 2007, golang 1.2.2/1.3rc2.

**Comment by bbigras** [comment]
go version go1.3 windows/amd64
Windows 7
Excel 2007 12.0.4518.1014

**Comment by nivrrex** [comment]
I conducted tests on other computers, but also the emergence of this error. (Windows7 64-bit, golang 1.3 amd64, excel2007) 
In this system, I re-set the target platform to compile X86 architecture. 

``` Batch
set GOARCH=386 
cd C:\go\src\ 
C:\go\src\make.bat 
```

After recompiling the test code, do not have this problem arise. 

According to my tracking code wrong position, an error occurred at the location "oleutil.MustCallMethod", but "oleutil.MustGetProperty" operate without this problems.
I guess it should be referenced "github.com/mattn/go-ole" library failed to consider the 64-bit environment (or I did not find) 
(excel2007 is a 32-bit application, excel 2010 version has a 64-bit environment, but without this test environment around me.) 

If want to solve, need to hack "go-ole" libraries.
Temporary solutions that generate executable x86 platform.

---

Has already been reflected in a similar problem. "Fatal error: freelist empty"
https://github.com/mattn/go-ole/issues/18

**Comment by bbigras** [comment]
I don't have the `freelist empty` error with Go 386.

I created a xlsm file with 2 sheets but it seems the module only see 1 and outputs weird data when I try to read cell 1,1.

Sheet 1
![image](https://cloud.githubusercontent.com/assets/24027/3357899/bc420d00-fad7-11e3-83e2-ec390c404a71.png)

Sheet 2
![image](https://cloud.githubusercontent.com/assets/24027/3357907/d4aa5942-fad7-11e3-8e0a-5752543e03dd.png)

I'm testing this on XP.
go version go1.3 windows/386
Excel 2000 9.0.4402 SR-1

By the way you can use the `Batch` or `Batchfile` keyword to highlight Windows' commands.

``` go
package main

import (
    "fmt"
    "github.com/nivrrex/excel"
)

func main() {
    var excelFile excel.Excel

    e, err := excelFile.Open("d:\\test.xlsm")
    if err != nil {
        panic(err)
    }
    defer e.Close()

    e, _ = (e.SheetsCount())
    fmt.Printf("e.Count = %d\n", e.Count)

    e, _ = e.Sheet(1)

    v, _ := e.Cells(1, 1)
    fmt.Println(v)
}
```

```
D:\Dev\go\go-test-excel>go run texc.go
e.Count = 1
PK♥♦!³‘í2ƒ☺Š♣‼Ü☺[Content_Types].xml ¢Ø☺( ☻ÌTÑNÂ0¶}7ñ▼–¾š­€‰1†Áƒâ£’ˆ▼PÚ♂[èÚ¦·àø{ï6!Bæ☻âƒ/[šæžsî9÷v8.♂↔mÀcnMÊúIE`¤U¹Y¦ì}ö∟ßƒ0Jhk e[@6▲]_
```

**Comment by nivrrex** [comment]
You can use "e, _ = e.Sheet(x)" to select the "x" sheet.
example: 

``` golang
e, _ = e.Sheet(2)
v, _ := e.Cells(1, 1)
fmt.Println(v)
```

For the weird data, I need to find appropriate environment for testing.
What's the result for this code ?

``` golang
fmt.Println(&v)
```
